name: Flutter SDK Action
description: Flutter SDK GitHub Action, currently only supports Android and Linux
author: Ahmad Rifa'i
branding:
  icon: smartphone
  color: blue
  
inputs:
  channel:
    description: Flutter SDK channel
    required: false
    default: stable
  
outputs:
  channel:
    value: ${{ steps.set_channel.outputs.channel }}
    description: The selected Flutter SDK channel

runs:
  using: composite
  steps:
    - name: Set Channel Output to GITHUB_ENV
      id: set_channel
      shell: bash
      run: echo "CHANNEL=${{ inputs.channel }}" >> $GITHUB_ENV

    - name: Install Flutter SDK Stable Channel
      if: ${{ env.CHANNEL == 'stable' }}
      uses: docker://ghcr.io/arifai/flutter:stable
      with:
        args: flutter --version
    
    - name: Install Flutter SDK Beta Channel
      if: ${{ env.CHANNEL == 'beta' }}
      uses: docker://ghcr.io/arifai/flutter:beta
      with:
        args: flutter --version