name: Flutter SDK Action
description: Flutter SDK GitHub Action, currently only supports Android and Linux
author: Ahmad Rifa'i
branding:
  icon: smartphone
  color: blue
  
inputs:
  channel:
    description: Flutter SDK channel
    required: false
    default: stable
  
outputs:
  channel:
    value: ${{ steps.flutter-sdk-action.outputs.channel }}
    description: The selected Flutter SDK channel

runs:
  using: composite
  steps:
    - name: Install Flutter SDK Stable Channel
      if: ${{ inputs.channel == 'stable' }}
      uses: docker://ghcr.io/arifai/flutter:stable
    
    - name: Install Flutter SDK Beta Channel
      if: ${{ inputs.channel == 'beta' }}
      uses: docker://ghcr.io/arifai/flutter:beta
    
    - name: Export PATH to Environment
      shell: bash
      run: |
        export PUB_CACHE=${{ github.workspace }}/.pub-cache \
        export PATH='$PATH:$PUB_CACHE/bin'